In [66]:
import pandas as pd

data = [
    {"name": "John", "age": 25, "city": "New York"},
    {"name": "Alice", "age": 32, "city": "San Francisco"},
    {"name": "Nate", "age": 41, "city": "Seattle"},
]

data.extend([{"name": "Emily", "age": 29, "city": "Boston"}])

df = pd.DataFrame(data)

df

    name  age           city
0   John   25       New York
1  Alice   32  San Francisco
2   Nate   41        Seattle
3  Emily   29         Boston

In [67]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     4 non-null      int64
 2   city    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

             age
count   4.000000
mean   31.750000
std     6.800735
min    25.000000
25%    28.000000
50%    30.500000
75%    34.250000
max    41.000000

In [68]:
df.to_csv('sample_data.csv', index=False)

In [69]:
df_loaded = pd.read_csv('sample_data.csv')

print("\nLoaded DataFrame:")
df_loaded

Loaded DataFrame:

    name  age           city
0   John   25       New York
1  Alice   32  San Francisco
2   Nate   41        Seattle
3  Emily   29         Boston

In [70]:
print("\nColumn Names:",df.columns.tolist())
print("\nFirst 2 rows:")
print(df.head(2))
print("\nLast 2 rows:")
print(df.tail(2))

Column Names: ['name', 'age', 'city']

First 2 rows:
    name  age           city
0   John   25       New York
1  Alice   32  San Francisco

Last 2 rows:
    name  age     city
2   Nate   41  Seattle
3  Emily   29   Boston

In [71]:
print("\nAge Statistics:")
print("Average age:",df['age'].mean())
print("Minimum age:",df['age'].min())
print("Maximum age:",df['age'].max())
print("Standard Deviation:",df['age'].std())
print("Variance:",df['age'].var())
print("Skewness:",df['age'].skew())
print("Kurtosis:",df['age'].kurt())

Age Statistics:
Average age: 31.75
Minimum age: 25
Maximum age: 41
Standard Deviation: 6.800735254367722
Variance: 46.25
Skewness: 0.9816108738225432
Kurtosis: 1.2324324324324323

In [72]:
print("\nPeople older than 30:")
print(df[df['age'] > 30])

print("\nSortedby age (descending):")
print(df.sort_values(by='age', ascending=False))

People older than 30:
    name  age           city
1  Alice   32  San Francisco
2   Nate   41        Seattle

Sortedby age (descending):
    name  age           city
2   Nate   41        Seattle
1  Alice   32  San Francisco
3  Emily   29         Boston
0   John   25       New York

In [73]:
age30 = df[df["age"] < 30]
age30["name"]

0     John
3    Emily
Name: name, dtype: object

In [74]:
print("\nSsrted by age (descending):")
print(df.sort_values(by='age', ascending=False))

Ssrted by age (descending):
    name  age           city
2   Nate   41        Seattle
1  Alice   32  San Francisco
3  Emily   29         Boston
0   John   25       New York

In [75]:
# Highest age
df.sort_values(by="age", ascending=False).head(1)

   name  age     city
2  Nate   41  Seattle

In [76]:
print("\nCity distribution:")
print(df['city'].value_counts())

City distribution:
city
New York         1
San Francisco    1
Seattle          1
Boston           1
Name: count, dtype: int64

In [77]:
df['new_value']=df['age']*2
df

    name  age           city  new_value
0   John   25       New York         50
1  Alice   32  San Francisco         64
2   Nate   41        Seattle         82
3  Emily   29         Boston         58

In [78]:
variable_1=df['age']
print(type(variable_1))

<class 'pandas.core.series.Series'>

In [79]:
df["age_group"] = pd.cut(
    df["age"],
    bins=[20, 25, 30, 35, 40, 45],
    labels=["20-25", "26-30", "31-35", "36-40", "41-45"],
)
print("DataFrame with age groups:")
df

DataFrame with age groups:

    name  age           city  new_value age_group
0   John   25       New York         50     20-25
1  Alice   32  San Francisco         64     31-35
2   Nate   41        Seattle         82     41-45
3  Emily   29         Boston         58     26-30

In [80]:
df.drop('age_group',axis=1,inplace=True)

In [81]:
df

    name  age           city  new_value
0   John   25       New York         50
1  Alice   32  San Francisco         64
2   Nate   41        Seattle         82
3  Emily   29         Boston         58

In [82]:
additional_data=[
    {'name':'Nate','age':29,'city':'Austin','new_value':58},
    {'name':'Peter','age':27,'city':'Boston','new_value':54},
    {'name':'Marshall','age':24,'city':'Austin','new_value':48},
    {'name':'Mark','age':28,'city':'New York','new_value':56},
    {'name':'Diana','age':43,'city':'Dallas','new_value':86},
    {'name':'Chris','age':39,'city':'Chicago','new_value':66},
    {'name':'Brown','age':32,'city':'Portland','new_value':64},
    {'name':'Steve','age':38,'city':'Austin','new_value':68},
    {'name':'Whitney','age':37,'city':'Portland','new_value':74},
    {'name':'John','age':25,'city':'New York','new_value':50},
    {'name':'Alice','age':33,'city':'San Francisco','new_value':66},
    {'name': 'to be removed', "age": 44, 'city':"Portland",'new_value':None}
]

new_records=pd.DataFrame(additional_data)
df=pd.concat([df,new_records],ignore_index=True)
df

             name  age           city  new_value
0            John   25       New York       50.0
1           Alice   32  San Francisco       64.0
2            Nate   41        Seattle       82.0
3           Emily   29         Boston       58.0
4            Nate   29         Austin       58.0
5           Peter   27         Boston       54.0
6        Marshall   24         Austin       48.0
7            Mark   28       New York       56.0
8           Diana   43         Dallas       86.0
9           Chris   39        Chicago       66.0
10          Brown   32       Portland       64.0
11          Steve   38         Austin       68.0
12        Whitney   37       Portland       74.0
13           John   25       New York       50.0
14          Alice   33  San Francisco       66.0
15  to be removed   44       Portland        NaN

In [83]:
df.dropna(inplace=True)

In [84]:
df=df.rename(columns={'new_value':'salary'})
df['salary']=df['salary'].astype(str)+'k'

In [85]:
df

        name  age           city salary
0       John   25       New York  50.0k
1      Alice   32  San Francisco  64.0k
2       Nate   41        Seattle  82.0k
3      Emily   29         Boston  58.0k
4       Nate   29         Austin  58.0k
5      Peter   27         Boston  54.0k
6   Marshall   24         Austin  48.0k
7       Mark   28       New York  56.0k
8      Diana   43         Dallas  86.0k
9      Chris   39        Chicago  66.0k
10     Brown   32       Portland  64.0k
11     Steve   38         Austin  68.0k
12   Whitney   37       Portland  74.0k
13      John   25       New York  50.0k
14     Alice   33  San Francisco  66.0k

In [86]:
new_data=[
    {'name':"Sarah",'age':None,'city':"Houston",'salary':'50.0k'},
    {'name':"Jessy",'age':None,'city':"New York",'salary':'68.0k'},
    {'name':"Cody",'age':None,'city':"Chicago",'salary':'55.0k'}
]
df=pd.concat([df,pd.DataFrame(new_data)],ignore_index=True)
df

        name   age           city salary
0       John    25       New York  50.0k
1      Alice    32  San Francisco  64.0k
2       Nate    41        Seattle  82.0k
3      Emily    29         Boston  58.0k
4       Nate    29         Austin  58.0k
5      Peter    27         Boston  54.0k
6   Marshall    24         Austin  48.0k
7       Mark    28       New York  56.0k
8      Diana    43         Dallas  86.0k
9      Chris    39        Chicago  66.0k
10     Brown    32       Portland  64.0k
11     Steve    38         Austin  68.0k
12   Whitney    37       Portland  74.0k
13      John    25       New York  50.0k
14     Alice    33  San Francisco  66.0k
15     Sarah  None        Houston  50.0k
16     Jessy  None       New York  68.0k
17      Cody  None        Chicago  55.0k

In [88]:
boston_filtered=df[
    (df['city']=='Boston') & (df['age'].between(25,30)) & (df['salary'].str.replace('k','').astype(float)>34)
]